# Generated by Django 6.0.4 on 2026-05-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('personal_id_number', models.CharField()),
                ('enroll_year', models.IntegerField()),
                ('enroll_id', models.IntegerField()),
            ],
        ),
    ]
