# Generated by Django 6.0.4 on 2026-05-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exam_subject_grade_exam_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
